import numpy as np
a=np.array([10,20,30,40,50])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
print(b.shape)
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.ndim)
print(c.shape)