import numpy as np
a = np.array([1, 2, 3])
print(a.dtype)
b = np.array([1.5, 2.5, 3.5])
print(b.dtype)
c = np.array([1, 2, 3], dtype="float")
print(c)
print(c.dtype)
d = np.array([1.2, 2.7, 3.9])
e = d.astype(int)
print(e)
print(e.dtype)
f = np.array([1, 0, 3])
g = f.astype(bool)
print(g)
print(g.dtype)