import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b)))
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
print(np.concatenate((c,d),axis=0))
print(np.concatenate((c,d),axis=1))
print(np.stack((a,b),axis=0))
print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.dstack((a,b)))