import numpy as np
a=np.array([40,10,30,20])
print(np.sort(a))
b=np.array(["banana","apple","mango"])
print(np.sort(b))
c=np.array([True,False,True])
print(np.sort(c))
d=np.array([[3,2,1],[6,5,4]])
print(np.sort(d))
e=np.array([5,9,1,7,2])
print(np.sort(e))