a=tuple(map(int,input("Enter elements: ").split()))
print("Tuple:",a)
print("Type:",type(a))
print("Length:",len(a))
print("First Element:",a[0])
print("Last Element:",a[-1])
print("Slice:",a[1:4])
print("Count of First Element:",a.count(a[0]))
print("Index of First Element:",a.index(a[0]))
print("Maximum:",max(a))
print("Minimum:",min(a))
print("Sum:",sum(a))
for i in a:
    print(i,end=" ")