a=tuple(map(int,input("Enter elements: ").split()))
b=tuple(map(int,input("Enter more elements: ").split()))
print("Tuple 1:",a)
print("Tuple 2:",b)
print("Concatenation:",a+b)
print("Repetition:",a*2)
print("Membership:",20 in a)
print("Length:",len(a))
print("Maximum:",max(a))
print("Minimum:",min(a))
print("Sum:",sum(a))
print("Sorted:",tuple(sorted(a)))
print("Reversed:",tuple(reversed(a)))
for i in a:
    print(i,end=" ")