a=set(map(int,input("Enter first set: ").split()))
b=set(map(int,input("Enter second set: ").split()))
print("Set A:",a)
print("Set B:",b)
print("Union:",a.union(b))
print("Intersection:",a.intersection(b))
print("Difference A-B:",a.difference(b))
print("Difference B-A:",b.difference(a))
print("Symmetric Difference:",a.symmetric_difference(b))
print("Subset:",a.issubset(b))
print("Superset:",a.issuperset(b))
print("Disjoint:",a.isdisjoint(b))